import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import { notFound } from 'next/navigation'
import { ChevronRight, ArrowRight } from 'lucide-react'
import ProductDetail from '@/components/ProductDetail'
import { getProductBySlug, getProducts, getProductSlugs } from '@/lib/api/products'
import { PRODUCT_CARD_IMAGE } from '@/lib/data'
import { formatPrice } from '@/lib/format'
import { SITE_URL, CURRENCY } from '@/lib/config'

/** Prerender known product pages at build time. Falls back to on-demand for unknown slugs. */
export async function generateStaticParams() {
  try {
    const slugs = await getProductSlugs()
    return slugs.map((slug) => ({ slug }))
  } catch {
    // API unreachable at build time (e.g. backend redeploying) — render on-demand instead.
    return []
  }
}

/**
 * `params` is a Promise in Next 16 — synchronous access was removed, not merely deprecated.
 * `PageProps<'/shop/[slug]'>` is generated by `next typegen`.
 */
export async function generateMetadata(props: PageProps<'/shop/[slug]'>): Promise<Metadata> {
  const { slug } = await props.params
  const product = await getProductBySlug(slug)
  if (!product) return { title: 'Product not found' }

  const lowest = Math.min(...product.variants.map((v) => v.price_cents))
  return {
    title: product.name,
    description: `${product.tagline}. ${product.description.slice(0, 150)}… From ${formatPrice(lowest)}.`,
    alternates: { canonical: `/shop/${product.slug}` },
    openGraph: {
      type: 'website',
      title: `${product.name} | Pholar Natural`,
      description: product.tagline,
      url: `/shop/${product.slug}`,
      images: [{ url: product.images[0].url, alt: product.images[0].alt }],
    },
  }
}

export default async function ProductPage(props: PageProps<'/shop/[slug]'>) {
  const { slug } = await props.params
  const product = await getProductBySlug(slug)
  if (!product) notFound()

  const others = (await getProducts()).filter((p) => p.id !== product.id)
  const lowest = Math.min(...product.variants.map((v) => v.price_cents))

  return (
    <div className="mx-auto max-w-7xl px-5 py-10 md:px-16 md:py-16">
      {/* Product structured data (doc §1.1.2). */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'Product',
            name: product.name,
            description: product.description,
            image: product.images.map((i) => `${SITE_URL}${i.url}`),
            brand: { '@type': 'Brand', name: 'Pholar Natural' },
            sku: product.variants[0]?.sku,
            offers: product.variants.map((v) => ({
              '@type': 'Offer',
              name: `${product.name} — ${v.weight_label}`,
              sku: v.sku,
              price: (v.price_cents / 100).toFixed(2),
              priceCurrency: CURRENCY,
              availability:
                v.stock_count > 0
                  ? 'https://schema.org/InStock'
                  : 'https://schema.org/OutOfStock',
              url: `${SITE_URL}/shop/${product.slug}`,
            })),
            ...(product.rating && {
              aggregateRating: {
                '@type': 'AggregateRating',
                ratingValue: product.rating,
                reviewCount: 128,
              },
            }),
          }),
        }}
      />

      <nav aria-label="Breadcrumb" className="mb-8">
        <ol className="flex flex-wrap items-center gap-2 font-label-sm text-label-sm text-on-surface-variant">
          <li>
            <Link href="/" className="hover:text-primary">
              Home
            </Link>
          </li>
          <ChevronRight className="h-3.5 w-3.5" aria-hidden="true" />
          <li>
            <Link href="/shop" className="hover:text-primary">
              Shop
            </Link>
          </li>
          <ChevronRight className="h-3.5 w-3.5" aria-hidden="true" />
          <li aria-current="page" className="font-semibold text-primary">
            {product.name}
          </li>
        </ol>
      </nav>

      <ProductDetail product={product} />

      {others.length > 0 && (
        <section className="mt-20 border-t border-outline-variant pt-16">
          <div className="mb-8 flex items-end justify-between gap-4">
            <h2 className="font-headline-lg text-headline-lg-mobile text-primary md:text-headline-lg">
              You may also like
            </h2>
            <Link href="/shop" className="group flex items-center gap-2 font-label-sm text-label-sm text-primary">
              View Shop
              <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" aria-hidden="true" />
            </Link>
          </div>

          <ul className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {others.map((p) => (
              <li key={p.id}>
                <Link
                  href={`/shop/${p.slug}`}
                  className="group flex gap-4 rounded-2xl bg-surface-container-low p-4 transition-colors hover:bg-surface-container"
                >
                  <div className="relative h-24 w-24 shrink-0 overflow-hidden rounded-xl">
                    <Image
                      src={PRODUCT_CARD_IMAGE[p.slug] ?? p.images[0].url}
                      alt=""
                      fill
                      sizes="96px"
                      className="object-cover transition-transform duration-500 group-hover:scale-105"
                    />
                  </div>
                  <div className="flex flex-col justify-center">
                    <h3 className="font-headline-md text-body-lg text-on-surface">{p.name}</h3>
                    <p className="font-body-md text-[13px] italic text-on-surface-variant">{p.tagline}</p>
                    <p className="mt-1 font-body-md text-body-md font-bold text-primary">
                      From {formatPrice(Math.min(...p.variants.map((v) => v.price_cents)))}
                    </p>
                  </div>
                </Link>
              </li>
            ))}
          </ul>
        </section>
      )}

      <p className="mt-10 text-center font-label-sm text-label-sm uppercase tracking-wider text-on-surface-variant">
        All prices in {CURRENCY} · Free shipping over {formatPrice(5000)} · From {formatPrice(lowest)}
      </p>
    </div>
  )
}
